# Horizontal Pod Autoscaler for Claims Service
# Automatically scales pods based on CPU/Memory utilization and custom metrics
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: claims-service-hpa
  labels:
    app: claims-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: claims-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  # Scale based on CPU utilization
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Scale based on Memory utilization
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  # Optional: Scale based on custom metrics like request count
  # Requires metrics server and custom metrics adapter
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 4
        periodSeconds: 30
      selectPolicy: Max

---
# Vertical Pod Autoscaler (VPA) - Optional for AI workload optimization
# Automatically adjusts CPU/memory requests based on actual usage
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: claims-service-vpa
  labels:
    app: claims-service
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: claims-service
  updatePolicy:
    updateMode: "Auto"  # Can be "Auto", "Recreate", or "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: claims-service
      minAllowed:
        cpu: 250m
        memory: 512Mi
      maxAllowed:
        cpu: 2000m
        memory: 4Gi
      controlledResources:
      - cpu
      - memory
